export const homeObjOne = {
  id: 'oferta',
  lightBg: false,
  LightText: false,
  lightTextDesc: false,
  topLine: 'Strony Wizytówki',
  headline: 'Unlimited Transactions with zero fees',
  description: 'get acces to our exclusive app that allows you to send unlimited money',
  buttonLabel: 'GetStarted',
  imgStart: false, 
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: 'o-nas',
  lightBg: true,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'get acces to our exclusive app that allows you to send unlimited money',
  buttonLabel: 'GetStarted',
  imgStart: true, 
  img: require('../../images/svg-2.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: true,
};