
export const homeObjOne = {
  id: 'oferta',
  lightBg: false,
  LightText: false,
  lightTextDesc: false,
  topLine: 'Strony Wizytówki',
  headline: 'Strona wizytówka Twojej firmy',
  description: 'Idealne rozwiązanie dla firm i osób prywatnych, które chcą szybko i niewielkim kosztem zaistnieć w sieci. \n\n CENA PAKIETU: 1000zł netto' ,
  buttonLabel: 'Skontaktuj się i zamów',
  imgStart: false, 
  img: require('../../images/svg-1.svg').default,
  alt: 'Strony Wizytówki',
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: 'sklepy-internetowe',
  lightBg: true,
  lightText: true,
  lightTextDesc: true,
  topLine: 'E-commerce',
  headline: 'Twój sklep internetowy szyty na miarę',
  description: 'Głównym celem sklepu internetowego jest przedstawienie oferowanych produktów oraz przekonanie odwiedzającego sklep do zrobienia zakupów. Projekt sklepu internetowego powinien być dostosowany graficznie do rodzaju asortymentu, a przy tym interfejs musi pozwalać na intuicyjne poruszanie się po sklepie. \n\n CENA PAKIETU: od 2500zł netto',
  buttonLabel: 'Skontaktuj się i zamów',
  imgStart: true, 
  img: require('../../images/svg-2.svg').default,
  alt: 'E-commerce',
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjThree = {
  id: 'kontakt',
  lightBg: false,
  LightText: false,
  lightTextDesc: false,
  topLine: 'Masz pytania lub chcesz podjąć współprace?',
  headline: 'Skontaktuj się z nami',
  description: "Zadzwoń: +48 881 185 247 \n Napisz do nas na festdevpl@gmail.com \n lub skorzystaj z formularza kontaktowego" ,
  buttonLabel: 'Formularz Kontaktowy',
  imgStart: false, 
  img: require('../../images/svg-3.svg').default,
  alt: 'Kontakt',
  dark: true,
  primary: true,
  darkText: true,
};